### ISSUE TITLE
Portfolio Deployment

### ISSUE THREAD

**Issue by Shahid-Bagwan** [Shahid-Bagwan/Portfolio#8]
### The Portfolio website  [Live Demo](https://shahid-bagwan.github.io/Portfolio/)

**Comment by LionRouge1** [comment]
Hi @Shahid-Bagwan, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
